<?php

namespace MyCompany\PublishBundle\Repository;

use Doctrine\ORM\EntityRepository;
use MyCompany\PublishBundle\Entity\Post;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

}
